batch: false
compile: true
cuda: 0
data:
  batch_size: 512
  data_dir: null
  entry_start: null
  entry_stop: null
  eval_batch_size: 512
  eval_cut: null
  max_size: 100
  pt_topk: false
  test:
  - perfNano_TTbar_PU200.110X_set5.root
  - perfNano_TTbar_PU200.110X_set6.root
  train:
  - perfNano_TTbar_PU200.110X_set0.root
  - perfNano_TTbar_PU200.110X_set1.root
  - perfNano_TTbar_PU200.110X_set2.root
  - perfNano_TTbar_PU200.110X_set3.root
  train_cut: null
  val:
  - perfNano_TTbar_PU200.110X_set4.root
data_transformation:
  gen_met_std:
  - 63.918
  - 63.918
  puppi_cands_cont_std:
  - 10.687
  - 10.687
  - 1.417
  - 1.0
deterministic: false
event_weighting:
  name: DensityWeightHist
log_base: null
log_name: null
model:
  activation: ReLU
  charge_embed_dim: 2
  cont_embed_dim: 12
  dropout_p: 0
  embed_dim: 16
  final_activation: Identity
  final_bias: false
  latent_len: 8
  name: Perceiver
  num_heads: 2
  num_layers: 4
  pdgid_embed_dim: 2
  weight_dim: 0
  widening_factor: 1
num_threads: 1
optimizer:
  beta1: 0.9
  beta2: 0.95
  fused: true
  learning_rate: 0.01
  weight_decay: 0.1
sanity_check: false
seed: -1
training:
  early_stopping_patience: 50
  loss: MSELoss
  lr_cosine_annealing: false
  max_grad_norm: 1
  num_epochs: 500
  t_0: 10
  t_mult: 2
