src: /u/user/seyang/work/meteor/deepmeteor/logs/train_231017-004736_perceiver-vanilla-pillbug
data:
  data_dir: null
  max_size: 100
  pt_topk: true
  train_cut: "genMet_pt > 150"
  eval_cut: null
  batch_size: 256
  eval_batch_size: 512
  entry_start: null
  entry_stop: null
  test:
  - perfNano_TTbar_PU200.110X_set5.root
  - perfNano_TTbar_PU200.110X_set6.root
  train:
  - perfNano_TTbar_PU200.110X_set0.root
  - perfNano_TTbar_PU200.110X_set1.root
  - perfNano_TTbar_PU200.110X_set2.root
  - perfNano_TTbar_PU200.110X_set3.root
  val:
  - perfNano_TTbar_PU200.110X_set4.root
data_transformation:
  gen_met_std:
  - 63.918
  - 63.918
  puppi_cands_cont_std:
  - 10.687
  - 10.687
  - 1.417
  - 1.0
event_weighting:
  name: DensityWeightHist
<<<<<<< HEAD:config/retrain/test.yaml
||||||| 21c1c6d:config/density-weight.yaml
log_base: null
log_name: null
mode: run
model:
  charge_embed_dim: 8
  cont_embed_dim: 40
  dropout_prob: 0.01
  name: Transformer
  num_heads: 4
  num_layers: 2
  pdgid_embed_dim: 16
num_threads: 1
=======
log_base: null
log_name: null
mode: run
model:
  name: Transformer
  depth: 16
  num_heads: 4
  num_layers: 1
  dropout_prob: 0.01
num_threads: 1
>>>>>>> 4b12bf9b2a43d122f8b6e63395377fd152a61f0f:config/density-weight.yaml
optimizer:
  beta1: 0.9
  beta2: 0.95
  fused: true
  learning_rate: 0.003
  weight_decay: 0.1
training:
  loss: MSELoss
  max_grad_norm: 1
  num_epochs: 100
log_base: null
log_name: null
num_threads: 1
seed: -1
sanity_check: false
batch: false
