src: /u/user/seyang/work/meteor/deepmeteor/logs/train_231017-004736_perceiver-vanilla-pillbug
data:
  data_dir: null
  max_size: 100
  pt_topk: true
  train_cut: "genMet_pt > 150"
  eval_cut: null
  batch_size: 256
  eval_batch_size: 512
  entry_start: null
  entry_stop: null
  test:
  - perfNano_TTbar_PU200.110X_set5.root
  - perfNano_TTbar_PU200.110X_set6.root
  train:
  - perfNano_TTbar_PU200.110X_set0.root
  - perfNano_TTbar_PU200.110X_set1.root
  - perfNano_TTbar_PU200.110X_set2.root
  - perfNano_TTbar_PU200.110X_set3.root
  val:
  - perfNano_TTbar_PU200.110X_set4.root
data_transformation:
  gen_met_std:
  - 63.918
  - 63.918
  puppi_cands_cont_std:
  - 10.687
  - 10.687
  - 1.417
  - 1.0
event_weighting:
  name: DensityWeightHist
optimizer:
  beta1: 0.9
  beta2: 0.95
  fused: true
  learning_rate: 0.003
  weight_decay: 0.1
training:
  loss: MSELoss
  max_grad_norm: 1
  num_epochs: 100
log_base: null
log_name: null
num_threads: 1
seed: -1
sanity_check: false
batch: false
